services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: [redis-server, --appendonly, yes]
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
volumes:
  db_data:
  redis_data:
