services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chat-app
      POSTGRES_PASSWORD: chat-app
      POSTGRES_DB: chat-app
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  db_data:
  redis_data: